### ISSUE TITLE
Can't import completed HAP back into Media Encoder.

### ISSUE THREAD

**Issue by PLangvardt** [disguise-one/hap-encoder-adobe-cc#11]
See error message:
![image](https://user-images.githubusercontent.com/43389333/46577782-ffa2fa00-c9b3-11e8-9865-3529de18265f.png)

**Comment by GregBakker** [comment]
This project doesn't add HAP import abilities to Adobe CC - just encoding, ie export.

If you believe there's a problem with the files being created, let us know what version / build of Media Encoder you're using, and if you've tried any other software to playback the imported files.

Also please note happlugin@disguise.one is a better address to send questions to.

**Comment by DouglasHeriot** [comment]
Adobe says the latest release of After Effects (and maybe Media Encoder?) support HAP decoding natively now! https://adobe-video.uservoice.com/forums/911311-after-effects/suggestions/33853372-support-the-hap-codec
