### ISSUE TITLE
FPS stored and reported incorrectly externally

### ISSUE THREAD

**Issue by GregBakker** [disguise-one/hap-encoder-adobe-cc#15]
From @exscriber:

Hap-CC: codec_time_base=1499/37500 (~25,0167 fps), and d3 also show 25,0167 fps.
QT-Hap: codec_time_base=1/25 (25fps)

This is likely something to do with how MovieWriter calculates and stores fps.

**Comment by GregBakker** [comment]
LGTM; would like further details [and to keep an eye on] the deprecation warning  though

**Comment by twhittock** [comment]
PR merged for this issue, should be resolved.
