### ISSUE TITLE
AME hap export cut last frame

### ISSUE THREAD

**Issue by exscriber** [disguise-one/hap-encoder-adobe-cc#2]
It happen with AE to AME render, and File to File transcode
from 60sec 25 fps file it render only 1499 frames, not 1500 like QT Hap (and other codecs)
file to play with: https://www.dropbox.com/s/kw0al6es559ra95/Comp%201.mp4?dl=0

**Comment by GregBakker** [comment]
Could you try an export to h264 and see if that drops the last frame too
please?

I have observed that behaviour from AME previously; it may not be a codec
thing.

Thanks,
Greg

**Comment by exscriber** [comment]
Exports from https://www.dropbox.com/s/kw0al6es559ra95/Comp%201.mp4?dl=0 file (1500 frames with timecode text):
h264: 00:00:00:00 - 00:00:59:24 1500 frames
QT Hap: 00:00:00:00 - 00:00:59:24 1500 frames
FlexRes: 00:00:00:00 - 00:00:59:24 1500 frames
Hap plugin: 00:00:00:00 - 00:00:59:23 1499 frames

In/out markers in AME not touched:
AME itself set markers to 00:00:00:00 - 00:01:00:00, but correctly render file as 00:00:00:00 - 00:00:59:24

AME 12.0.1 version for windows if it matter - not last one because of QT support

**Comment by GregBakker** [comment]
Thanks,

I'll be able to take a look at the cause in code on Friday.

Greg

**Comment by exscriber** [comment]
Partial sulution:  for even fps like 25, 30, etc
```
main.cpp:
-        renderParams.inEndTime = exportInfoP->endTime;
+        renderParams.inEndTime = exportInfoP->endTime + frameRateDenominator; //add one more frame to render
```
but it not mimic QT hap or h264 with 29.97 framerates, only with 25fps

PS: with patch it start to mimic FlexRes behavior - rite for 25fps, wrong for 29.97

**Comment by GregBakker** [comment]
That patch looks correct though; I'll have to look at the QT hap source and see where it's inconsistent.

I'll make that change; thanks for the investigation.

**Comment by GregBakker** [comment]
I've added the change; still need to check if QT hap was doing the right thing. The Adobe API seems slightly inconsistent here too.

**Comment by exscriber** [comment]
Hi Greg
I was wrong about issue roots:
SDK work as expected - so patch is wrong and not needed. AME render all 1500 frames without it.

But something not right with time_base setting in muxer,
You can see it with ffprobe -show_format -show_streams 1.mov

Hap-CC: codec_time_base=1499/37500 (~25,0167 fps), and d3 also show 25,0167 fps.
QT-Hap: codec_time_base=1/25 (25fps)

And slight fps increase cause last frame hiding in AE, d3, other software...

**Comment by GregBakker** [comment]
Older code I started with [using a different non-multithreaded api] had the non-inclusive end code as well; so maybe there's something subtle here.
The main thing is are we exporting the same frames as (say) an Adobe-written H264 export.
The fps-reporting issue is probably a different matter. I'll raise a separate issue on that.

**Comment by exscriber** [comment]
Hap-CC AME test render with release 1.0.8-rc4 version: 1minute 25fps 1500 frames file
d3 and ffprobe: both show 1500 frames exist in file. With wrong fps, but no frames missed.

So Hap-CC not cut frames during AME render. No renderParams.inEndTime adjust needed.

What looks like missing last frame: most likely caused by issue #15.
