### ISSUE TITLE
Export with embeded audio

### ISSUE THREAD

**Issue by exscriber** [disguise-one/hap-encoder-adobe-cc#21]
Will be great to export video with embeded audio track.

**Comment by GregBakker** [comment]
Soliciting feedback here regarding desired interleaving behaviour - the current intention is to match ffmpeg, ie tightly interleave audio and video frames.

**Comment by bangnoise** [comment]
My tuppence: I think interleaved makes sense for most scenarios, but would be good to have that confirmed for a few different players.

**Comment by GregBakker** [comment]
Merged and undergoing testing. Can be found on the releases page as the 1.0.9-RC1 prerelease.

**Comment by Harvey3141** [comment]
It would also be useful to have the ability to embed non-interleaved mono channels. Currently, it's not possible to export anything over 5.1 without embedding the audio manually with ffmpeg.

**Comment by GregBakker** [comment]
@Harvey3141 I'll raise a separate issue for >5.1 support. Out of interest, why is non-interleaved desired? Are you using a tool that wants to a contiguous set of blocks for that mono channel?
