### ISSUE TITLE
Plugin not working after been installed in the right folder

### ISSUE THREAD

**Issue by rubenplazagarcia** [disguise-one/hap-encoder-adobe-cc#3]
After installing the plugin in the right path in a Mac with O.S Sierra and AE and ME CC2018 , Hap Video is not available in the list of video formats of ME

/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/

The machine is used as a render machine own by the National. 

The issue is odd because I installed the plugin in other machine they owns an it works perfectly.

**Comment by bangnoise** [comment]
@rubenplazagarcia after you ran the installer the first time, was the plugin present at /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/HapEncoderPlugin.bundle but not working, or was it not installed?

**Comment by rubenplazagarcia** [comment]
Yes @bangnoise, the plugin was in the right folder. 
![dsc_0990](https://user-images.githubusercontent.com/43670023/46401481-03552900-c6f5-11e8-8943-5ba66899be02.JPG)

**Comment by rubenplazagarcia** [comment]
Last Friday, I advised the National to uninstall  the plugin, AE and ME and make fresh install.

**Comment by rubenplazagarcia** [comment]
Hola @bangnoise 

I sent an email to the National yesterday to ask about this issue but not answer yet.

**Comment by GregBakker** [comment]
cannot reproduce atm; likely out of date wrt 1.2.0-rc1 [the next release]
