### ISSUE TITLE
odd frame rates when exporting through Adobe 2018 and 2019

### ISSUE THREAD

**Issue by samkriemelmeyer** [disguise-one/hap-encoder-adobe-cc#31]
Hello!

have you ever seen odd HAP frame rates like 30.199 or 30.099 come from Adobe products? PC or Mac 2018 and 2019 seem do all do this.

compressor seems to do fine with it.

avf batch also does fine.

(codec v12)

cheers,

sam

**Comment by GregBakker** [comment]
Hi Sam,

I've found and fixed a problem *like* this with a prototype I'm working on (which supported import) - and it's possible there's an analog of it in the released version (round-tripping to adobe).

I'll look into this in the next few days.

Greg

**Comment by samkriemelmeyer** [comment]
Thank you Greg.  It is a curious one. 
Gig is approaching fast... your help is appreciated.

**Comment by GregBakker** [comment]
It appears that the exported packet structures are correct presentation time-wise, but common tools (windows etc) calculate the frame-rate by (number of frames) / (sum of internal durations) - but at the moment the last frame duration is unset internally. So the framerate is calculated as (number of frames)/(duration excluding last frame), giving a slightly wrong framerate.

This may not be an issue in your case (or likely in most cases) as players most likely compute a timestamp, and then lookup the frame that should be showing at that time. So it's a display issue more than anything else.

I'll be making a build with a fix soonish anyway.

**Comment by samkriemelmeyer** [comment]
good detective work!

**Comment by exscriber** [comment]
Fix in 1.0.9 prerelease version cure odd framerates (it noted as 29.97 fix, but other affected as well). At least during my internal test runs - fps looks ok.
Please take a look at 1.0.9, and if it doesn`t work for you - let us know.

Nick

**Comment by twhittock** [comment]
Closing since no update - assuming 1.0.9 resolved the issue. Reopen if not. Thanks.
