### ISSUE TITLE
Not Working Adobe 2020 (After Effects, Premiere and Media Encoder)

### ISSUE THREAD

**Issue by daesquina** [disguise-one/hap-encoder-adobe-cc#48]
Hey, I've just installed both Quicktime component and the 1.2.0-rc1 encoder, but cannot get it to show.
Once After Effects gets launched i get this error message:

![Screen Shot 2020-07-31 at 12 23 14 PM](https://user-images.githubusercontent.com/69048709/89052105-9845ff00-d32b-11ea-9645-bfee6d7901fa.png)

Also, digging up a bit on the Adobe Logs, I've found some information that I cannot say if they are important, but anyway...

File: Plugin Loading.log
root: documents/adobe/premiere pro/14.0/

Loading /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/HAPPremierePlugin.bundle
Loading from disk...
No loaders recognized this plugin, so the plugin is set to Ignore.

and

Loading /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/HAPAfterEffectsPlugin.bundle
Loading from disk...
No loaders recognized this plugin, so the plugin is set to Ignore.

Presets files (.epr) are located at documents/adobe/adobe media encoder/14.0/Presets
All Adobe was installed on default location
Running High Sierra 10.13.6
Premiere Pro version: 14.2
After Effects Version: 17.1
Media Encoder Version: 14.3.1

Thank You for your time :)

**Comment by GregBakker** [comment]
Hmm we haven't tested on High Sierra; and in fact our deployment target is set at 10.14 (Mojave) - this is very likely (an) issue preventing it running on High Sierra.

I'll see if I can put together a build targeting High Sierra; it's going to be difficult supporting that going forward though. In fact Mojave is also lacking things we'd like to use.

Out of interest, are you locked to High Sierra due to the need for 32-bit quicktime plugin support?

**Comment by daesquina** [comment]
I thought it could be it.
In fact, i'm not locked in high sierra... i could upgrade the OS, but haven't done because of two things: Older Mac Pro (2010), and always with a project running, so upgrading in the middle of a project is asking for some trouble...

back to HAP, i can see quicktime can export it.. was loonking to fix this adobe issue, çause I'll have to export 96 different movies next week, so having to export them all on a intermediate codec and then manually export them all will be a huge hassle... will try to find some batch exporter to minimize the stress of exporting one by one...

thank you for your time and effort.

**Comment by GregBakker** [comment]
We're just putting together a High Sierra build; it might fix your issue. Watch this space :)

**Comment by bangnoise** [comment]
@daesquina could you give this build a go and report back - thanks!

[HapEncoder-1.2.0-rc1-macOS.pkg.zip](https://github.com/disguise-one/hap-encoder-adobe-cc/files/5008189/HapEncoder-1.2.0-rc1-macOS.pkg.zip)

**Comment by daesquina** [comment]
Nothing has changed... same After Effects error and still no HAP anywhere
should I "uninstall" somehow the codec and previous attempts? (not sure how to do it)...

**Comment by bangnoise** [comment]
Ah bother - OK, I'll take a deeper look over the weekend. Thanks for trying.

**Comment by daesquina** [comment]
I thank you for spending the time and effort...

**Comment by bangnoise** [comment]
@GregBakker can you update the foundation submodule for this repo for this documentation fix? thanks!

**Comment by bangnoise** [comment]
@daesquina this build works for me on 10.13 - hopefully it does for you too...

[HapEncoder-1.2.0-rc1-macOS.pkg.zip](https://github.com/disguise-one/hap-encoder-adobe-cc/files/5012825/HapEncoder-1.2.0-rc1-macOS.pkg.zip)

**Comment by daesquina** [comment]
and it worked... :) 
thank you all so freaking much!

**Comment by GregBakker** [comment]
Sweet, good to hear :)
