### ISSUE TITLE
Effects not included in Export from Premiere 2020

### ISSUE THREAD

**Issue by jpaleNHL** [disguise-one/hap-encoder-adobe-cc#49]
Exporting sequences from Premiere Pro 14.0 in standard HAP codec.  Dissolves and other effects do not reliably appear in the encodes, even when sequence is fully rendered.  Workaround has been to export in Apple Pro Res, then use Adobe Media Encoder to convert to HAP.

HapEncoder 1.2.0 release candidate 1
Adobe CC 2020/Adobe Premiere 14.0
MacOS Catalina 10.15.3

**Comment by bangnoise** [comment]
A minimal Premiere project we can use to recreate this issue would be very helpful, if you're able, thanks!

**Comment by jpaleNHL** [comment]
A project with media or just the project file?  I had 16 sequences all exhibit this problem in my latest project.  Its not a lot of footage (mostly graphics files) for a giant screen presentation for the NHL. No fancy effects.


John Pale
Finishing Editor
NHL Studios

________________________________

**Comment by GregBakker** [comment]
Hi John,

we're not particularly experienced users of Premiere etc ourselves - in general we just use the narrow range of functionality needed to export a movie. We wouldn't be confident putting together a dissolve and knowing we were duplicating your situation.

It would really help if you could create a new project that has the simplest possible fade that triggers the problem - even from one still image to another - and zip it up along with any assets it needs. You should be able to attach the zip to this issue.

Thanks!

**Comment by jpaleNHL** [comment]
https://we.tl/t-S9X8PaRouY

Here is a minimal sequence with a few media files.


John Pale
Finishing Editor
NHL Studios

________________________________

**Comment by GregBakker** [comment]
Thanks John, that's super helpful. I can replicate the problem on my machine, and also see that prores4444 export for the same file works fine on my system.

I have no idea what's causing the issue at the moment, but am looking into it.

**Comment by GregBakker** [comment]
Hi John, we have a handle on the problem now.e're obtaining frames from Premiere as RGBA [even though we're not exporting the A]. The assumption

**Comment by GregBakker** [comment]
Hi John, we have a handle on the problem now.

We're obtaining frames from Premiere as RGBA, even though we're not exporting the alpha channel for the subcodec you're using.

In your test case the fade is encoded as transparency - ie in the alpha channel - which we're ignoring.

I haven't been able to find a sequence setting in Premiere that creates a matted sequence (ie with premultiplied alpha), which would fix your problem. If you know how to remove the transparency within Premiere itself please let me know; haven't found it in the references yet. Might well be something blindingly obvious and simple in the UI.

We're working on a fix at the moment, but maybe this gives you some ideas on how to work around it for now.

**Comment by GregBakker** [comment]
Here's one Premiere user's method for solving a similar problem (see bottom of page):

https://forums.creativecow.net/docs/forums/post.php?forumid=3&postid=993632&univpostid=993632&pview=t

I hope there's an easier way than this though.

**Comment by jpaleNHL** [comment]
Thanks for taking the time to look into this. It's appreciated.

There really isn't any way to do what you are suggesting in Premiere.  As far as the Creative Cow post goes, duplicating clips and turning off layers isn't really a good solution. It will get in the way of editing efficiency to have to jump through those hoops all day.  Much simpler to just export in a mezzanine codec like Apple Pro Res, then batch convert everything to HAP for the playback system.

Until this is fixed,  you should really warn people not to export directly from Premiere Pro sequences.  This is really basic editing stuff that will affect almost everyone.  Few editors would expect a problem like this to occur as every other codec export would handle this sort of thing without the end user even thinking about it.  We had some time constraints and almost didn't QC the exports that carefully, being that the sequences were so simple, but luckily we caught that many of the fades were not present before they were put in use. We were able to shift gears and work around it in time, but others might not be so lucky. It's a very big issue for Premiere.  Probably less so for After Effects and Adobe Media Encoder.




John Pale
Finishing Editor
NHL Studios

________________________________

**Comment by GregBakker** [comment]
Bizarrely this hasn't really cropped up before - and I can confirm the same issue exists going back nearly two years. I guess that people have generally been using the codec in AME for transcoding, rather than an editing scenario, or as you say we would have heard about it pretty soon.

We have a fix in the works - I'll attach a pre-release here [it's unsigned, so you'll need to right-click and choose 'open' from the menu there; macos won't let you install it without jumping through hoops].

**Comment by GregBakker** [comment]
Alternatively you can wait until late tomorrow, when more eyes have been over the fix, and there's a signed release.

[HapEncoder-1.2.0-rc1-macOS.pkg.zip](https://github.com/disguise-one/hap-encoder-adobe-cc/files/5013035/HapEncoder-1.2.0-rc1-macOS.pkg.zip)

**Comment by bangnoise** [comment]
Here's a signed version which allows easier installation -

[HapEncoder-1.2.0-rc2-macOS.pkg.zip](https://github.com/disguise-one/hap-encoder-adobe-cc/files/5013045/HapEncoder-1.2.0-rc2-macOS.pkg.zip)

**Comment by jpaleNHL** [comment]
Thanks. I actually already installed the unsigned one and tried the test sequence I sent you.  Seems to solve the issue.  Testing with more complex sequences in a little while.


John Pale
Finishing Editor
NHL Studios

________________________________

**Comment by jpaleNHL** [comment]
Thanks again.  Just re-exported a bunch of the problem sequences from the other day and it worked correctly on all of them.  I'll be doing a lot HAP exports the next couple of months for the National Hockey League and will alert you if anything comes up.


John Pale
Finishing Editor
NHL Studios

________________________________

**Comment by GregBakker** [comment]
Cheers John, and thanks for putting together the test case; it was invaluable.
