### ISSUE TITLE
quality settings

### ISSUE THREAD

**Issue by GregBakker** [disguise-one/hap-encoder-adobe-cc#5]
Tracking the progress of the quality settings that were introduced in pr #4

Issue to be closed after testing complete + mac / win builds uploaded.

**Comment by bangnoise** [comment]
I see the PR uses the IterativeClusterFit for "high" quality - it is extremely slow with minimal gains compared to the ClusterFit. Unless anyone can produce evidence otherwise to support its inclusion, I'd suggest it not be used as it will considerably degrade user experience.

**Comment by GregBakker** [comment]
@eclazi you might be interested in this one :)

**Comment by GregBakker** [comment]
@exscriber you might be interested in this too :)

**Comment by GregBakker** [comment]
fixed in pr #9
