### ISSUE TITLE
Uninstall this plugin

### ISSUE THREAD

**Issue by hananafif** [disguise-one/hap-encoder-adobe-cc#58]
How to uninstall this plugin? due incompatibility with m1, I want to clean uninstall this plugin, please help, I'm using adobe cc 2023 and M1 Pro device

**Comment by bangnoise** [comment]
Delete the plugin from /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/

**Comment by hananafif** [comment]
There's no other folder except my plugin
<img width="785" alt="image" src="https://github.com/disguise-one/hap-encoder-adobe-cc/assets/30401150/22c16fd8-d9fe-4d4a-b113-76b293d82bbe">


when I launch AE, it shows warn like this
<img width="542" alt="image" src="https://github.com/disguise-one/hap-encoder-adobe-cc/assets/30401150/efe92502-aad9-462c-b074-471c5cc89686">

**Comment by bangnoise** [comment]
I think in your screenshot you have not selected the MediaCore folder so you can't see the contents.

**Comment by hananafif** [comment]
Sorry, wrong path, here's the correct one
<img width="785" alt="image" src="https://github.com/disguise-one/hap-encoder-adobe-cc/assets/30401150/251f2684-5b66-4f8b-aa1b-e3e319447d07">

**Comment by bangnoise** [comment]
Screenshots aren't hugely helpful as I can't see the full path. The plugin is installed to `/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore` - that is the system-wide Library folder at the top level of your disk, not the Library folder in your home directory.

AE also loads plugins from a folder named Plug-Ins alongside the AE application - this is not the location the installer uses, but if the plugin is really not in the MediaCore folder then as far as I know, that's the only other possible location. Perhaps try the Adobe forum if you're still stuck.

**Comment by hananafif** [comment]
Thanks, I found it

For anyone wondering how to uninstall, here's the guide

1. Open finder
2. expand "Go" dropdown
3. hit "Go to folder..."
4. paste the given path `/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore`
5. and delete HAP files

TYSM for your help :))
