### ISSUE TITLE
Uninstall encoder on Mac

### ISSUE THREAD

**Issue by werbeagent** [disguise-one/hap-encoder-adobe-cc#62]
As Silicon-Macs are not provided i would like to uninstall the encoder – but i can´t find any way how to do that.

Could anyone help? THNX

**Comment by bangnoise** [comment]
Remove the encoder from /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore

**Comment by werbeagent** [comment]
Thank you bangnoise
