### ISSUE TITLE
doc/user_guide is missing hap-logo.svg

### ISSUE THREAD

**Issue by bangnoise** [disguise-one/hap-encoder-adobe-cc#8]
Results in a missing image in doc/user_guide/README.md

**Comment by GregBakker** [comment]
Originally the User Guide was intended to be built and installed; for which the image was working.

While it's nice to have a local nice-looking version of this, maybe most people will be accessing via the github page anyway - in which case maybe I should drop the local user guide altogether and replace the header with an embedded image.

Will ask around to see if anyone's actually looked at it :)

**Comment by GregBakker** [comment]
Updated to use .png on landing page. Github doesn't allow svg in markdown because of cross-site scripting attacks, boo
